### ISSUE TITLE
bind key"N"

### ISSUE THREAD

**Issue by all85100** [OciXCrom/SimpleMenu#2]
Can you add a menu command to bind the function of the button "N", use the judgment, if the player buys the night vision device, then the button "N" just turns on the night vision device, if the player does not buy the night vision device then the button "N" is Open a menu command.

**Comment by OciXCrom** [comment]
The plugin isn't used on keys, it's used on the commands that are assigned on those keys. You can't force-bind players' keys. If you want to use the "N" key, assing it to the "nightvision" command which is used by most players.

**Comment by all85100** [comment]
do you know ?use the judgment, if the player buys the night vision device, then the button "N" just turns on the night vision device, if the player does not buy the night vision device then the button "N" is Open a menu command.

**Comment by OciXCrom** [comment]
That is not how the plugin works. I can't add such an option for that command only. Either deal with it or use a different command.

**Comment by all85100** [comment]
I know !thanks!
