### ISSUE TITLE
Sometimes 'exit' option is not showing

### ISSUE THREAD

**Issue by nicxes** [OciXCrom/SimpleMenu#3]
Sometimes when I open the menu, don't show the exit option in the menu, I need to re-open the menu to see the option.

![image](https://user-images.githubusercontent.com/8798356/84841432-ac060200-b018-11ea-98bc-b1998c2583a9.png)

![image](https://user-images.githubusercontent.com/8798356/84841331-63e6df80-b018-11ea-97fc-43e2eee11da5.png)

**Comment by OciXCrom** [comment]
Let me see how you configured the menu.

**Comment by nicxes** [comment]
```
[New Menu = Admin Menu]

[Menu Settings]
MENU_TITLE = \r[PGaming.net] \yMenu de ADMIN:
MENU_EXIT = Salir
MENU_OPEN = say /pgadmin, pg_admin
MENU_FLAG = ADMIN_KICK
MENU_ITEMS_PER_PAGE = 0
MENU_ITEM_FORMAT = %item%
MENU_PREFIX = !g[PG]!n
MENU_SOUND = 
MENU_REOPEN = 0
MENU_NOACCESS = No tienes acceso a este comando.

[Menu Items]
"\yExpulsar \wJugador" "pg_admin_kick" "ADMIN_KICK"
"\yBanear \wJugador" "" "ADMIN_BAN"
"\ySlap/Matar \wJugador" "pg_admin_slay" "ADMIN_SLAY"
"\dEquipo del Jugador" "" "ADMIN_SLAY"
#blank 0
"\wMenu de \yMIX" "say !mix" "ADMIN_KICK"
"\wMenu de \yMAPAS" "pg_admin_maps" "ADMIN_MAP"
#blank 0
"\dComandos de Voz" "" "ADMIN_RCON"
"\dComandos del Servidor" "" "ADMIN_RCON"
```

**Comment by OciXCrom** [comment]
Probably caused by `MENU_ITEMS_PER_PAGE` or adding `#blank` in the menu. This is a bug with the default AMXX menu system. Try using `#blank 1` or remove the blanks completely.
